# Generated by Django 2.2.4 on 2020-07-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
            ],
            options={
                'verbose_name': '省',
                'verbose_name_plural': '省',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.Province', verbose_name='省')),
            ],
            options={
                'verbose_name': '市',
                'verbose_name_plural': '市',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.City', verbose_name='市')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.Province', verbose_name='省')),
            ],
            options={
                'verbose_name': '区',
                'verbose_name_plural': '区',
            },
        ),
    ]
