# Generated by Django 2.2.4 on 2020-07-07 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0005_auto_20200704_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_user', to=settings.AUTH_USER_MODEL, verbose_name='对应账号'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='名称')),
                ('phone', models.CharField(max_length=64, unique=True, verbose_name='电话')),
                ('head', models.URLField(blank=True, default='', verbose_name='头像')),
                ('openid', models.CharField(blank=True, default='', max_length=64, verbose_name='openid')),
                ('unionid', models.CharField(blank=True, default='', max_length=64, verbose_name='unionid')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='对应邮箱')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_user', to=settings.AUTH_USER_MODEL, verbose_name='对应账号')),
            ],
            options={
                'verbose_name': '销售',
                'verbose_name_plural': '销售',
            },
        ),
    ]
