# Generated by Django 2.2.4 on 2020-06-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True, verbose_name='名称')),
                ('types', models.PositiveSmallIntegerField(choices=[(0, 'PDF文档'), (1, '视频mp4'), (2, '图片'), (3, 'DOC文档'), (4, 'Excel文档'), (5, '链接内容')], default=0, verbose_name='类型')),
                ('url', models.URLField(default='', verbose_name='地址链接')),
            ],
            options={
                'verbose_name': '资料',
            },
        ),
    ]
