# Generated by Django 2.2.4 on 2020-06-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '资料', 'verbose_name_plural': '资料'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': '课程', 'verbose_name_plural': '课程'},
        ),
        migrations.AlterField(
            model_name='package',
            name='title',
            field=models.CharField(max_length=127, unique=True, verbose_name='课程名称'),
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='课节名称')),
                ('intro', models.TextField(blank=True, default='', verbose_name='课节介绍')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='课序号')),
                ('cover', models.URLField(blank=True, default='', verbose_name='封面图片')),
                ('thum_img', models.URLField(blank=True, default='', verbose_name='缩略图')),
                ('material', models.ManyToManyField(to='course.Material', verbose_name='课节资料')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Package', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课节',
                'verbose_name_plural': '课节',
                'unique_together': {('package', 'title')},
            },
        ),
    ]
