# Generated by Django 2.2.4 on 2020-06-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200630_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='is_online',
        ),
    ]
