# Generated by Django 2.2.4 on 2020-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True, verbose_name='名称')),
                ('province', models.CharField(default='', max_length=127, verbose_name='所在省')),
                ('city', models.CharField(default='', max_length=127, verbose_name='所在城市')),
                ('address', models.CharField(default='', max_length=255, verbose_name='机构地址')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
    ]
