# Generated by Django 2.2.4 on 2020-06-30 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='对应机构')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Teacher', verbose_name='对应老师')),
            ],
            options={
                'verbose_name': '机构老师',
                'verbose_name_plural': '机构老师',
            },
        ),
        migrations.CreateModel(
            name='InstStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='对应机构')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Manager', verbose_name='对应学生')),
            ],
            options={
                'verbose_name': '机构学生',
                'verbose_name_plural': '机构学生',
            },
        ),
        migrations.CreateModel(
            name='InstManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='对应机构')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Manager', verbose_name='对应管理员')),
            ],
            options={
                'verbose_name': '机构管理员',
                'verbose_name_plural': '机构管理员',
            },
        ),
        migrations.CreateModel(
            name='InstConcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('concat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Contact', verbose_name='对应联系人')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='对应机构')),
            ],
            options={
                'verbose_name': '机构联系人',
                'verbose_name_plural': '机构联系人',
            },
        ),
    ]
