# Generated by Django 2.2.4 on 2020-07-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('course', '0004_remove_package_is_online'),
        ('institution', '0002_instconcat_instmanager_inststudent_instteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterUniqueTogether(
            name='instconcat',
            unique_together={('institution', 'concat')},
        ),
        migrations.AlterUniqueTogether(
            name='instmanager',
            unique_together={('institution', 'manager')},
        ),
        migrations.AlterUniqueTogether(
            name='inststudent',
            unique_together={('institution', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='instteacher',
            unique_together={('institution', 'teacher')},
        ),
        migrations.CreateModel(
            name='InstCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabel', models.BooleanField(default=False, verbose_name='是否可以使用课程')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='过期时间')),
                ('actived_date', models.DateField(blank=True, null=True, verbose_name='激活时间')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='对应机构')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Package', verbose_name='机构解锁的课程')),
            ],
            options={
                'verbose_name': '机构课程',
                'verbose_name_plural': '机构课程',
                'unique_together': {('institution', 'package')},
            },
        ),
    ]
