# Generated by Django 2.2.4 on 2020-07-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20200701_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='city',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='province',
        ),
    ]
