# Generated by Django 2.2.4 on 2020-07-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20200704_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
