# Generated by Django 2.2.4 on 2020-07-04 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20200704_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inststudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.Student', verbose_name='对应学生'),
        ),
    ]
