# Generated by Django 2.2.4 on 2020-07-07 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_auto_20200707_0917'),
        ('institution', '0008_auto_20200704_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='dispatch_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分配时间'),
        ),
        migrations.AddField(
            model_name='institution',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.Sales', verbose_name='分配的销售'),
        ),
    ]
