# Generated by Django 2.2.4 on 2020-07-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='名称')),
                ('grade', models.PositiveSmallIntegerField(choices=[(0, '1年级'), (1, '2年级'), (0, '3年级'), (0, '4年级'), (0, '5年级'), (0, '6年级')], default=0, verbose_name='年级')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('master_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_teacher', to='role.Teacher', verbose_name='班主任')),
                ('slave_teacher', models.ManyToManyField(related_name='slave_teacher', to='role.Teacher', verbose_name='辅助老师')),
                ('students', models.ManyToManyField(to='role.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '资料',
                'verbose_name_plural': '资料',
            },
        ),
    ]
