# Generated by Django 2.2.4 on 2020-07-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
    ]
