# Generated by Django 2.2.4 on 2020-07-01 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200701_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='master_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_teacher', to='institution.InstTeacher', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='slave_teacher',
            field=models.ManyToManyField(related_name='slave_teacher', to='institution.InstTeacher', verbose_name='辅助老师'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='institution.InstStudent', verbose_name='学生'),
        ),
    ]
