# Generated by Django 2.2.4 on 2020-07-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_package_is_online'),
        ('institution', '0003_auto_20200701_2329'),
        ('classroom', '0003_auto_20200701_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='packages',
            field=models.ManyToManyField(to='course.Package', verbose_name='所上课程'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'grade', 'institution')},
        ),
    ]
